[package]
name = "upload-client"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.1.0", features = ["cargo"] }
indicatif = "0.16.2"
serde_json = "1.0.78"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }

[[bin]]
name = "upload-client"
path = "src/main.rs"
